apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  chart:
    spec:
      version: "7.0.16"
  test:
    enable: false
  values:
    replicas: 1
    service:
      enabled: true
      port: 81
